language: node_js
node_js:
- '4'
- '6'
- '8'
- '9'
- '10'
jobs:
  include:
  - stage: release
    node_js: '8'
    deploy:
    - provider: npm
      email: simbo@simbo.de
      api_key: "${NPM_API_KEY}"
      on:
        tags: true
